services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'practical'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
      - ${PWD}/data/Dump20201103.sql:/docker-entrypoint-initdb.d/start.sql
volumes:
  my-db: